# Intro to Recommender Systems Lab

Complete the exercises below to solidify your knowledge and understanding of recommender systems.

For this lab, we are going to be putting together a user similarity based recommender system in a step-by-step fashion. Our data set contains customer grocery purchases, and we will use similar purchase behavior to inform our recommender system. Our recommender system will generate 5 recommendations for each customer based on the purchases they have made.

In [14]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import pdist, squareform

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/eduardoheros/lab-intro-recommender-systems/master/data/customer_product_sales.csv')

In [3]:
data.head()

   CustomerID FirstName   LastName  ...  ProductID           ProductName Quantity
0       61288      Rosa   Andersen  ...        229  Bread - Hot Dog Buns       16
1       77352     Myron     Murray  ...        229  Bread - Hot Dog Buns       20
2       40094     Susan  Stevenson  ...        229  Bread - Hot Dog Buns       11
3       23548    Tricia    Vincent  ...        229  Bread - Hot Dog Buns        6
4       78981     Scott      Burch  ...        229  Bread - Hot Dog Buns       20

[5 rows x 7 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68584 entries, 0 to 68583
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   68584 non-null  int64
 1   FirstName    68584 non-null  object
 2   LastName     68584 non-null  object
 3   SalesID      68584 non-null  int64
 4   ProductID    68584 non-null  int64
 5   ProductName  68584 non-null  object
 6   Quantity     68584 non-null  int64
dtypes: int64(4), object(3)
memory usage: 3.7+ MB

## Step 1: Create a data frame that contains the total quantity of each product purchased by each customer.

You will need to group by CustomerID and ProductName and then sum the Quantity field.

In [5]:
data_grouped=data.groupby(["CustomerID","ProductName"],as_index=False)["Quantity"].sum()
data_grouped.head()

   CustomerID                    ProductName  Quantity
0          33               Apricots - Dried         1
1          33              Assorted Desserts         1
2          33        Bandage - Flexible Neon         1
3          33  Bar Mix - Pina Colada, 355 Ml         1
4          33         Beans - Kidney, Canned         1

## Step 2: Use the `pivot_table` method to create a product by customer matrix.

The rows of the matrix should represent the products, the columns should represent the customers, and the values should be the quantities of each product purchased by each customer. You will also need to replace nulls with zeros, which you can do using the `fillna` method.

In [37]:
pivot_table=pd.pivot_table(data_grouped,values="Quantity",index="ProductName",columns="CustomerID",fill_value=0)
pivot_table

CustomerID                         33     200    264    ...  98159  98185  98200
ProductName                                             ...
Anchovy Paste - 56 G Tube              0      0      0  ...      0      0      0
Appetizer - Mini Egg Roll, Shrimp      0      0      0  ...      0      0      0
Appetizer - Mushroom Tart              0      0      0  ...      0     25      0
Appetizer - Sausage Rolls              0      0      0  ...      0     25      0
Apricots - Dried                       1      0      0  ...      0      0      0
...                                  ...    ...    ...  ...    ...    ...    ...
Yeast Dry - Fermipan                   0      0      0  ...      0      0      0
Yoghurt Tubes                          0      0      0  ...     25      0      0
Yogurt - Blueberry, 175 Gr             0      1      0  ...      0      0      0
Yogurt - French Vanilla                1      0      0  ...      0      0     25
Zucchini - Yellow                      0      0      0  ...      0      0      0

[452 rows x 1000 columns]

## Step 3: Create a customer similarity matrix using `squareform` and `pdist`. For the distance metric, choose "euclidean."

In [39]:
squareform(pdist(pivot_table))

array([[  0.        , 279.99642855, 253.66907577, ..., 255.67166444,
        258.0910692 , 278.47800631],
       [279.99642855,   0.        , 271.49953959, ..., 265.7367118 ,
        279.55500353, 286.80655502],
       [253.66907577, 271.49953959,   0.        , ..., 245.27535547,
        253.01580978, 269.43644891],
       ...,
       [255.67166444, 265.7367118 , 245.27535547, ...,   0.        ,
        264.14200726, 268.28343221],
       [258.0910692 , 279.55500353, 253.01580978, ..., 264.14200726,
          0.        , 273.15014186],
       [278.47800631, 286.80655502, 269.43644891, ..., 268.28343221,
        273.15014186,   0.        ]])

## Step 4: Check your results by generating a list of the top 5 most similar customers for a specific CustomerID.

In [39]:
squareform(pdist(pivot_table))

## Step 5: From the data frame you created in Step 1, select the records for the list of similar CustomerIDs you obtained in Step 4.

## Step 6: Aggregate those customer purchase records by ProductName, sum the Quantity field, and then rank them in descending order by quantity.

This will give you the total number of each product purchased by the 5 most similar customers to the customer you selected in order from most purchased to least.

## Step 7: Filter the list for products that the chosen customer has not yet purchased and then recommend the top 5 products with the highest quantities that are left.

- Merge the ranked products data frame with the customer product matrix on the ProductName field.
- Filter for records where the chosen customer has not purchased the product.
- Show the top 5 results.

## Step 8: Now that we have generated product recommendations for a single user, put the pieces together and iterate over a list of all CustomerIDs.

- Create an empty dictionary that will hold the recommendations for all customers.
- Create a list of unique CustomerIDs to iterate over.
- Iterate over the customer list performing steps 4 through 7 for each and appending the results of each iteration to the dictionary you created.

##  Step 9: Store the results in a Pandas data frame. The data frame should a column for Customer ID and then a column for each of the 5 product recommendations for each customer.

## Step 10: Change the distance metric used in Step 3 to something other than euclidean (correlation, cityblock, consine, jaccard, etc.). Regenerate the recommendations for all customers and note the differences.